# Generated by Django 4.2.3 on 2023-07-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
