# Generated by Django 4.2.3 on 2023-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('L', 'Laptop'), ('W', 'Workstation')], default='L', help_text='Type of asset (Laptop or Workstation)', max_length=1)),
                ('manufacturer', models.CharField(choices=[('D', 'Dell'), ('H', 'HP'), ('L', 'Lenovo')], default='H', help_text='Manufacturer of asset (HP, DELL, Lenovo, etc)', max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(help_text='Price of asset in rupees')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('I', 'Checked in'), ('O', 'Checked out')], default='I', max_length=1)),
                ('department', models.CharField(choices=[('O', 'Operations'), ('S', 'Sales'), ('A', 'Accounting'), ('I', 'IT')], max_length=1)),
            ],
        ),
    ]
