# Generated by Django 4.2.3 on 2023-07-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
    ]
