# Generated by Django 4.2.3 on 2023-07-12 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_asset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of asset purchase'),
            preserve_default=False,
        ),
    ]
