# Generated by Django 4.2.3 on 2023-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_asset_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
