# Generated by Django 4.2.3 on 2023-07-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_asset_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status of asset', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='checkout_status',
            field=models.CharField(choices=[('I', 'Checked in'), ('O', 'Checked out')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.status'),
        ),
    ]
