# Generated by Django 4.2.3 on 2023-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_category_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hdd',
            field=models.IntegerField(blank=True, help_text='Total HDD storage in asset', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice',
            field=models.IntegerField(blank=True, help_text='Invoice number of asset', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(default='core i5 8th gen', help_text='Processor specs', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.IntegerField(default=8, help_text='Total RAM in asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.CharField(blank=True, help_text='Serial number of asset', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='ssd',
            field=models.IntegerField(blank=True, help_text='Total SSD storage in asset', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Name of asset', max_length=200),
        ),
    ]
