# Generated by Django 4.2.3 on 2023-07-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='file',
            field=models.FileField(default='a', upload_to='attachements/'),
            preserve_default=False,
        ),
    ]
