# Generated by Django 4.2.3 on 2023-07-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of asset', max_length=200)),
                ('price', models.IntegerField(help_text='Price of asset in rupees')),
                ('purchase_date', models.DateField(help_text='Date of asset purchase')),
                ('accessory_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('serial', models.CharField(blank=True, help_text='Serial number of asset', max_length=200)),
                ('invoice', models.IntegerField(blank=True, help_text='Invoice number of asset', null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.employee')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.department')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manufacturer')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.status')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.supplier')),
            ],
        ),
    ]
