# Generated by Django 4.2.3 on 2023-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='type',
            field=models.CharField(choices=[('I', 'Check-in'), ('O', 'Check-out')], max_length=1),
        ),
    ]
