# Generated by Django 4.2.3 on 2023-07-25 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_checkout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.status'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='expected_return_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Expected return date of asset', null=True),
        ),
    ]
