# Generated by Django 4.2.3 on 2023-07-25 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0020_checkout_status_alter_checkout_expected_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now, help_text='Checkout/checkin date of asset')),
                ('type', models.CharField(choices=[('s', 'Asset'), ('c', 'Accessory')], default='s', max_length=1)),
                ('event', models.CharField(help_text='Event', max_length=50)),
                ('notes', models.CharField(blank=True, help_text='Notes regarding activity', max_length=500)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.asset')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
