# Generated by Django 4.2.3 on 2023-07-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.asset'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.employee'),
        ),
    ]
