# Generated by Django 4.2.3 on 2023-07-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_activity_asset_alter_activity_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-id']},
        ),
    ]
