# Generated by Django 4.2.3 on 2023-07-25 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now, help_text='Checkout/checkin date of asset'),
        ),
    ]
