# Generated by Django 4.2.3 on 2023-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_activity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Checkout/checkin date of asset'),
        ),
    ]
