# Generated by Django 4.2.3 on 2023-07-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_activity_asset_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
