# Generated by Django 4.2.3 on 2023-07-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0030_alter_activity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_audit_date', models.DateField(default=webapp.models.ScheduledAudit.date_in_future, help_text='Audit date of asset')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.asset')),
                ('assigned_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('G', 'General'), ('S', 'Special')], default='G', max_length=1)),
                ('audit_date', models.DateField(default=django.utils.timezone.now, help_text='Audit date of asset')),
                ('reason', models.CharField(blank=True, help_text='Reason for (special) audit', max_length=200)),
                ('results', models.CharField(help_text='Results of audit', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='audits/')),
                ('asset_string', models.CharField(blank=True, help_text='Asset string', max_length=500)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
