# Generated by Django 4.2.3 on 2023-07-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_scheduledaudit_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledaudit',
            options={'ordering': ['-next_audit_date', '-id']},
        ),
    ]
