# Generated by Django 4.2.3 on 2023-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_scheduledaudit_asset_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(help_text='Name of licensed software', max_length=300)),
                ('to_name', models.CharField(help_text='Name of person the software is licensed to', max_length=100)),
                ('to_email', models.EmailField(help_text='Email of person the software is licensed to', max_length=254)),
                ('license_type', models.CharField(choices=[('D', 'Dynamic'), ('P', 'Product key')], max_length=1)),
                ('seats', models.IntegerField(blank=True, help_text='Total seats allowed per license', null=True)),
                ('reference_no', models.CharField(blank=True, help_text='Reference no. of license', max_length=200)),
                ('purchase_date', models.DateField(help_text='Date of license purchase')),
                ('expiration_date', models.DateField(help_text='Date of license expiration')),
                ('cost', models.IntegerField(help_text='Cost of license')),
                ('billing_terms', models.CharField(help_text='Billing terms of license', max_length=300)),
                ('notes', models.CharField(help_text='Notes regarding license', max_length=500)),
            ],
        ),
    ]
