# Generated by Django 4.2.3 on 2023-08-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_license_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='kundan@ldplogistic.com', help_text='Email of employee', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default='Operations executive', help_text='Title/Designation of employee', max_length=300),
            preserve_default=False,
        ),
    ]
