# Generated by Django 4.2.3 on 2023-08-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_employee_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
