# Generated by Django 4.2.3 on 2023-08-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-id']},
        ),
    ]
